// Currencies Data
const List<Map<String, String>> currencyList = [
  // Americas
  {'code': 'USD', 'symbol': '\$', 'name': 'US Dollar (USD)'},
  {'code': 'CAD', 'symbol': 'C\$', 'name': 'Canadian Dollar (CAD)'},
  {'code': 'AUD', 'symbol': 'A\$', 'name': 'Australian Dollar (AUD)'},
  {'code': 'NZD', 'symbol': 'NZ\$', 'name': 'New Zealand Dollar (NZD)'},
  {'code': 'BRL', 'symbol': 'R\$', 'name': 'Brazilian Real (BRL)'},
  {'code': 'MXN', 'symbol': 'Mex\$', 'name': 'Mexican Peso (MXN)'},
  {'code': 'ARS', 'symbol': 'AR\$', 'name': 'Argentine Peso (ARS)'},
  {'code': 'CLP', 'symbol': 'CLP\$', 'name': 'Chilean Peso (CLP)'},
  // Europe
  {'code': 'EUR', 'symbol': '€', 'name': 'Euro (EUR)'},
  {'code': 'GBP', 'symbol': '£', 'name': 'British Pound (GBP)'},
  {'code': 'CHF', 'symbol': 'CHF', 'name': 'Swiss Franc (CHF)'},
  {'code': 'SEK', 'symbol': 'kr', 'name': 'Swedish Krona (SEK)'},
  {'code': 'NOK', 'symbol': 'kr', 'name': 'Norwegian Krone (NOK)'},
  {'code': 'DKK', 'symbol': 'kr', 'name': 'Danish Krone (DKK)'},
  {'code': 'PLN', 'symbol': 'zł', 'name': 'Polish Zloty (PLN)'},
  {'code': 'CZK', 'symbol': 'Kč', 'name': 'Czech Koruna (CZK)'},
  {'code': 'RUB', 'symbol': '₽', 'name': 'Russian Ruble (RUB)'},
  {'code': 'UAH', 'symbol': '₴', 'name': 'Ukrainian Hryvnia (UAH)'},
  {'code': 'RON', 'symbol': 'RON', 'name': 'Romanian Leu (RON)'},
  {'code': 'BGN', 'symbol': 'BGN', 'name': 'Bulgarian Lev (BGN)'},
  // Asia & Pacific
  {'code': 'JPY', 'symbol': '¥', 'name': 'Japanese Yen (JPY)'},
  {'code': 'CNY', 'symbol': '¥', 'name': 'Chinese Yuan (CNY)'},
  {'code': 'INR', 'symbol': '₹', 'name': 'Indian Rupee (INR)'},
  {'code': 'KRW', 'symbol': '₩', 'name': 'South Korean Won (KRW)'},
  {'code': 'SGD', 'symbol': 'S\$', 'name': 'Singapore Dollar (SGD)'},
  {'code': 'HKD', 'symbol': 'HK\$', 'name': 'Hong Kong Dollar (HKD)'},
  {'code': 'THB', 'symbol': '฿', 'name': 'Thai Baht (THB)'},
  {'code': 'MYR', 'symbol': 'RM', 'name': 'Malaysian Ringgit (MYR)'},
  {'code': 'IDR', 'symbol': 'Rp', 'name': 'Indonesian Rupiah (IDR)'},
  {'code': 'PHP', 'symbol': '₱', 'name': 'Philippine Peso (PHP)'},
  {'code': 'VND', 'symbol': '₫', 'name': 'Vietnamese Dong (VND)'},
  {'code': 'PKR', 'symbol': 'PKR', 'name': 'Pakistani Rupee (PKR)'},
  {'code': 'BDT', 'symbol': 'BDT', 'name': 'Bangladeshi Taka (BDT)'},
  // Middle East & Africa
  {'code': 'AED', 'symbol': 'AED', 'name': 'UAE Dirham (AED)'},
  {'code': 'MAD', 'symbol': 'MAD', 'name': 'Moroccan Dirham (MAD)'},
  {'code': 'SAR', 'symbol': 'SAR', 'name': 'Saudi Riyal (SAR)'},
  {'code': 'TRY', 'symbol': '₺', 'name': 'Turkish Lira (TRY)'},
  {'code': 'ILS', 'symbol': '₪', 'name': 'Israeli Shekel (ILS)'},
  {'code': 'ZAR', 'symbol': 'R', 'name': 'South African Rand (ZAR)'},
  {'code': 'EGP', 'symbol': 'E£', 'name': 'Egyptian Pound (EGP)'},
  {'code': 'NGN', 'symbol': 'NGN', 'name': 'Nigerian Naira (NGN)'},
  {'code': 'KES', 'symbol': 'KSh', 'name': 'Kenyan Shilling (KES)'},
];
